<?php

use InsuranceApp\ViewHelpers;

?>

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Your Quote</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="/normalize.css" rel="stylesheet" type="text/css">
    <link href="/styles.css" rel="stylesheet" type="text/css">
</head>
<body>
<?= ViewHelpers\NavigationViewHelper::displayNavbar() ?>

<h1>Your Quote</h1>
<section>
    <?= ViewHelpers\QuotesViewHelper::displaySingleQuote($singleQuote) ?>
    <div class="quoteButtons">
        <?= ViewHelpers\QuotesViewHelper::displayAcceptQuoteButton($id) ?>
        <a href=".">
            <button>Cancel</button>
        </a>
    </div>
</section>

</body>
</html>
